name: keeper
description: A flexible validation library for Dart, inspired by Zod. Supports chaining, custom rules, nullable values, and built-in validators for emails, phones, and more.
version: 0.0.1
repository: https://github.com/edunatalec/keeper

environment:
  sdk: ^3.7.0

scripts:
  coverage: |
    dart run test --coverage=coverage
    dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib
    genhtml -o coverage/html coverage/lcov.info
    open coverage/html/index.html

dependencies:

dev_dependencies:
  coverage: ^1.11.1
  lints: ^5.1.1
  test: ^1.25.15

topics:
  - validation
  - zod
